name: ci
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  java-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/java-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Run tests
        run: mvn -B -q clean test
